### ISSUE TITLE
Pre 1.3.0 issue - JsonException

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#107]
Just FYI...  With latest RRF and DSF from today...
```
[error] Failed to merge JSON: {"key":"fans","flags":"d99vn","result":[{"actualValue":0,"blip":0.10,"max":1.00,"min":0.10,"name":"PartCooling","requestedValue":0,"rpm":-1,"thermostatic":{"heaters":[],"highTemperature":null,"lowTemperature":null}},{"actualValue":1.00,"blip":0.10,"max":1.00,"min":0.10,"name":"HotEnd","requestedValue":1.00,"rpm":-1,"thermostatic":{"heaters":[1],"highTemperature":45.0,"lowTemperature":45.0}},{"actualValue":0.38,"blip":0.10,"max":1.00,"min":0.10,"name":"PSU","requestedValue":0.38,"rpm":-1,"thermostatic":{"heaters":[],"highTemperature":null,"lowTemperature":null}},null,null,null,null,null,null,null,{"actualValue":1.00,"blip":0,"max":1.00,"min":0.10,"name":"Bed LED","requestedValue":1.00,"rpm":-1,"thermostatic":{"heaters":[],"highTemperature":null,"lowTemperature":null}},{"actualValue":1.00,"blip":0,"max":1.00,"min":0.10,"name":"Front LED","requestedValue":1.00,"rpm":-1,"thermostatic":{"heaters":[],"highTemperature":null,"lowTemperature":null}}]}
   System.Text.Json.JsonException: Failed to deserialize property [FanThermostaticControl].HighTemperature (type Single) from JSON null
 ---> System.Text.Json.JsonException: The JSON value could not be converted to System.Single. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetSingle(Single& value)
   at System.Text.Json.Utf8JsonReader.GetSingle()
   at System.Text.Json.Serialization.Converters.JsonConverterSingle.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.HandleNull(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 282
   --- End of inner exception stack trace ---
   at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 287
   at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 244
   at DuetAPI.Machine.ModelCollectionHelper.UpdateFromJson(IList list, Type itemType, JsonElement jsonElement, Boolean ignoreSbcProperties) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelCollection.cs:line 208
   at DuetAPI.Machine.MachineModel.UpdateFromFirmwareModel(String key, JsonElement jsonElement) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/MachineModel.cs:line 162
   at DuetControlServer.Model.Updater.Run()
```

**Comment by gtjoseph** [comment]
Got another one...
```
[error] Failed to merge JSON: {"key":"move","flags":"d99vn","result":{"axes":[{"acceleration":3600.0,"babystep":0,"current":1750,"drivers":["0.0"],"homed":true,"jerk":1600.0,"letter":"X","machinePosition":230.000,"max":235.0,"maxProbed":false,"min":-235.0,"minProbed":false,"speed":16000.0,"userPosition":0,"visible":true,"workplaceOffsets":[0,0,0,0,0,0,0,0,0]},{"acceleration":3600.0,"babystep":0,"current":1750,"drivers":["0.1"],"homed":true,"jerk":1600.0,"letter":"Y","machinePosition":-222.000,"max":235.0,"maxProbed":false,"min":-235.0,"minProbed":false,"speed":16000.0,"userPosition":0,"visible":true,"workplaceOffsets":[0,0,0,0,0,0,0,0,0]},{"acceleration":150.0,"babystep":0,"current":1750,"drivers":["0.3","0.4","0.5"],"homed":true,"jerk":600.0,"letter":"Z","machinePosition":4.985,"max":420.0,"maxProbed":false,"min":0,"minProbed":false,"speed":1200.0,"userPosition":4.985,"visible":true,"workplaceOffsets":[0,0,0,0,0,0,0,0,0]}],"calibration":{"final":{"deviation":0,"mean":0},"initial":{"deviation":0,"mean":0},"numFactors":0},"compensation":{"fadeHeight":null,"file":null,"meshDeviation":{"deviation":0,"mean":0},"probeGrid":{"radius":-1.0,"xMax":230.0,"xMin":-230.0,"xSpacing":25.0,"yMax":225.0,"yMin":-225.0,"ySpacing":25.0},"type":"mesh"},"currentMove":{"acceleration":2546.0,"deceleration":2546.0,"requestedSpeed":60.0,"topSpeed":60.0},"daa":{"enabled":false,"minimumAcceleration":10.0,"period":0.0},"extruders":[{"acceleration":6000.0,"current":1500,"driver":"0.2","factor":1.0,"filament":"","jerk":1600.0,"nonlinear":{"a":0,"b":0,"upperLimit":0.20},"position":0,"pressureAdvance":0,"rawPosition":0,"speed":6000.0}],"idle":{"factor":0.5,"timeout":5.0},"kinematics":{"forwardMatrix":[[0.500,0.500,0],[0.500,-0.500,0],[0,0,1.000]],"inverseMatrix":[[0.500,0.500,0],[0.500,-0.500,0],[0,0,1.000]],"name":"coreXY"},"printingAcceleration":3600.0,"speedFactor":1.0,"travelAcceleration":3600.0,"workspaceNumber":1}}
  System.Text.Json.JsonException: Failed to deserialize property [MoveCompensation].MeshDeviation (type Nullable`1) from JSON {"deviation":0,"mean":0}
---> System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.Single]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a number.
  at System.Text.Json.Utf8JsonReader.TryGetSingle(Single& value)
  at System.Text.Json.Utf8JsonReader.GetSingle()
  at System.Text.Json.JsonPropertyInfoNullable`2.OnRead(ReadStack& state, Utf8JsonReader& reader)
  at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
  --- End of inner exception stack trace ---
  at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
  at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
  at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
  at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
  at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 282
  --- End of inner exception stack trace ---
  at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 287
  at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 244
  at DuetAPI.Machine.MachineModel.UpdateFromFirmwareModel(String key, JsonElement jsonElement) in /usr/src/3d/dc42/workspace/DuetSoftwareFramework/src/DuetAPI/Machine/MachineModel.cs:line 162
  at DuetControlServer.Model.Updater.Run()
```

**Comment by gtjoseph** [comment]
Confirmed fixed.  Thanks!
