### ISSUE TITLE
DCS 2.1.1 Crashing with System.ArgumentException: Property set method not found

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#128]
On behalf of user Garfield...
https://forum.duet3d.com/post/150029

UPDATE: I can reproduce the crash with just `M591 D0 P3 C"io5.in"`

Garfield's full comand was `M591 D0 P3 C"io5.in" S1 R70:130 L24.8 E3.0`

```

Apr 27 20:17:09 duet3 systemd[1]: duetcontrolserver.service: Succeeded.
--
  | Apr 27 20:33:50 duet3 systemd[1]: duetcontrolserver.service: Service RestartSec=30s expired, scheduling restart.
  | Apr 27 20:33:50 duet3 systemd[1]: duetcontrolserver.service: Scheduled restart job, restart counter is at 1.
  | Apr 27 20:33:50 duet3 systemd[1]: Stopped Duet Control Server.
  | Apr 27 20:33:50 duet3 systemd[1]: Started Duet Control Server.
  | Apr 27 20:33:51 duet3 DuetControlServer[763]: Duet Control Server v2.1.1
  | Apr 27 20:33:51 duet3 DuetControlServer[763]: Written by Christian Hammacher for Duet3D
  | Apr 27 20:33:51 duet3 DuetControlServer[763]: Licensed under the terms of the GNU Public License Version 3
  | Apr 27 20:33:51 duet3 DuetControlServer[763]: [info] Settings loaded
  | Apr 27 20:33:51 duet3 DuetControlServer[763]: [info] Environment initialized
  | Apr 27 20:33:51 duet3 DuetControlServer[763]: [info] Connection to Duet established
  | Apr 27 20:33:51 duet3 DuetControlServer[763]: [info] IPC socket created at /var/run/dsf/dcs.sock
  | Apr 27 20:33:53 duet3 DuetControlServer[763]: [fatal] Abnormal program termination
  | Apr 27 20:33:53 duet3 DuetControlServer[763]: [fatal] Update task faulted
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    System.ArgumentException: Property set method not found.
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 237
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.FilamentMonitor.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Sensors/FilamentMonitors/FilamentMoni
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 209
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.FilamentMonitor.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Sensors/FilamentMonitors/FilamentMoni
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelCollectionHelper.UpdateFromJson(IList list, Type itemType, JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 264
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.MachineModel.UpdateFromFirmwareModel(String key, JsonElement jsonElement) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/MachineModel.cs:line 149
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetControlServer.Model.Updater.Run() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/Model/Updater.cs:line 182
  | Apr 27 20:33:53 duet3 DuetControlServer[763]: [fatal] Update task faulted
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    System.ArgumentException: Property set method not found.
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 237
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.FilamentMonitor.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Sensors/FilamentMonitors/FilamentMoni
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 209
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.FilamentMonitor.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Sensors/FilamentMonitors/FilamentMoni
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelCollectionHelper.UpdateFromJson(IList list, Type itemType, JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.ModelObject.UpdateFromJson(JsonElement jsonElement, Boolean ignoreSbcProperties) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/Base/ModelObject.cs:line 264
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetAPI.Machine.MachineModel.UpdateFromFirmwareModel(String key, JsonElement jsonElement) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Machine/MachineModel.cs:line 149
  | Apr 27 20:33:53 duet3 DuetControlServer[763]:    at DuetControlServer.Model.Updater.Run() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/Model/Updater.cs:line 182
  | Apr 27 20:33:53 duet3 DuetControlServer[763]: [info] Application has shut down
  | Apr 27 20:33:53 duet3 systemd[1]: duetcontrolserver.service: Succeeded.
  | Apr 27 20:34:23 duet3 systemd[1]: duetcontrolserver.service: Service RestartSec=30s expired, scheduling restart.
  | Apr 27 20:34:23 duet3 systemd[1]: duetcontrolserver.service: Scheduled restart job, restart counter is at 2.
  | Apr 27 20:34:23 duet3 systemd[1]: Stopped Duet Control Server.
  | Apr 27 20:34:23 duet3 systemd[1]: Started Duet Control Server.
  | Apr 27 20:34:23 duet3 DuetControlServer[879]: Duet Control Server v2.1.1
  | Apr 27 20:34:23 duet3 DuetControlServer[879]: Written by Christian Hammacher for Duet3D
  | Apr 27 20:34:23 duet3 DuetControlServer[879]: Licensed under the terms of the GNU Public License Version 3
  | Apr 27 20:34:24 duet3 DuetControlServer[879]: [info] Settings loaded
  | Apr 27 20:34:24 duet3 DuetControlServer[879]: [info] Environment initialized
  | Apr 27 20:34:24 duet3 DuetControlServer[879]: [info] Connection to Duet established
  | Apr 27 20:34:24 duet3 DuetControlServer[879]: [info] IPC socket created at /var/run/dsf/dcs.sock
  | Apr 27 20:34:24 duet3 DuetControlServer[879]: [warn] Daemon: Out-of-order reply: ''
  | Apr 27 20:34:25 duet3 DuetControlServer[879]: [fatal] Abnormal program termination

```

**Comment by chrishamm** [comment]
Thanks, this is confirmed fixed in DSF 2.1.2.
