### ISSUE TITLE
Uncaught exception when parsing invalid gcode

### ISSUE THREAD

**Issue by beikeland** [chrishamm/DuetSoftwareFramework#17]
Accidentally inserted a `l` instead of `;` and DuetControlServer crashed when running the homing macro.

homex.g
```
G91
;G1 Z2.5 F600 S2
G1 S1 X-400 F180
G1 X5 F600
G1 S1 X-5 F300
lG1 Z-2.5 F180
G90
```
```
[info] Sent G28 X"", remaining space 1024, need 28
[info] Executing nested macro file '/opt/dsf/sd/sys/homex.g' on channel HTTP
[crit] Abnormal program termination:
SPI task terminated
[crit] DuetAPI.Commands.CodeParserException: Failed to parse minor GCode number (Z-25)
   at DuetAPI.Commands.Code..ctor(String codeString) in /home/christian/duet/DuetSoftwareFramework/src/DuetAPI/Commands/Code/Parser.cs:line 142
   at DuetControlServer.Commands.Code..ctor(String code) in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/Commands/Code.cs:line 26
   at DuetControlServer.FileExecution.BaseFile.ReadCode() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/FileExecution/BaseFile.cs:line 100
   at DuetControlServer.FileExecution.MacroFile.ReadCode() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/FileExecution/MacroFile.cs:line 156
   at DuetControlServer.SPI.ChannelInformation.ProcessRequests() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/SPI/Channel.cs:line 182
   at DuetControlServer.SPI.Interface.Run() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/SPI/Interface.cs:line 337
[warn] Connection error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at DuetControlServer.IPC.Processors.Subscription.Process() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/IPC/Processors/Subscription.cs:line 100
   at DuetControlServer.IPC.Server.ConnectionEstablished(Socket socket, Int32 id) in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/IPC/Server.cs:line 86
[warn] Connection error: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at DuetControlServer.IPC.Processors.Subscription.Process() in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/IPC/Processors/Subscription.cs:line 100
   at DuetControlServer.IPC.Server.ConnectionEstablished(Socket socket, Int32 id) in /home/christian/duet/DuetSoftwareFramework/src/DuetControlServer/IPC/Server.cs:line 86

```

**Comment by chrishamm** [comment]
Should be fixed in the latest DCS 1.0.2.1 as well. If the problem persists, feel free to reopen this issue.
